# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/braun/Developer/cos888/tscfl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/braun/Developer/cos888

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/braun/Developer/cos888/CMakeFiles /home/braun/Developer/cos888//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/braun/Developer/cos888/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tscfl

# Build rule for target.
tscfl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tscfl
.PHONY : tscfl

# fast build rule for target.
tscfl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/build
.PHONY : tscfl/fast

#=============================================================================
# Target rules for targets named tscfl_experiments

# Build rule for target.
tscfl_experiments: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tscfl_experiments
.PHONY : tscfl_experiments

# fast build rule for target.
tscfl_experiments/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl_experiments.dir/build.make CMakeFiles/tscfl_experiments.dir/build
.PHONY : tscfl_experiments/fast

experiments/tscfl_experiments.o: experiments/tscfl_experiments.cpp.o
.PHONY : experiments/tscfl_experiments.o

# target to build an object file
experiments/tscfl_experiments.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl_experiments.dir/build.make CMakeFiles/tscfl_experiments.dir/experiments/tscfl_experiments.cpp.o
.PHONY : experiments/tscfl_experiments.cpp.o

experiments/tscfl_experiments.i: experiments/tscfl_experiments.cpp.i
.PHONY : experiments/tscfl_experiments.i

# target to preprocess a source file
experiments/tscfl_experiments.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl_experiments.dir/build.make CMakeFiles/tscfl_experiments.dir/experiments/tscfl_experiments.cpp.i
.PHONY : experiments/tscfl_experiments.cpp.i

experiments/tscfl_experiments.s: experiments/tscfl_experiments.cpp.s
.PHONY : experiments/tscfl_experiments.s

# target to generate assembly for a file
experiments/tscfl_experiments.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl_experiments.dir/build.make CMakeFiles/tscfl_experiments.dir/experiments/tscfl_experiments.cpp.s
.PHONY : experiments/tscfl_experiments.cpp.s

src/lrp/tscfl_lrp.o: src/lrp/tscfl_lrp.cpp.o
.PHONY : src/lrp/tscfl_lrp.o

# target to build an object file
src/lrp/tscfl_lrp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp.cpp.o
.PHONY : src/lrp/tscfl_lrp.cpp.o

src/lrp/tscfl_lrp.i: src/lrp/tscfl_lrp.cpp.i
.PHONY : src/lrp/tscfl_lrp.i

# target to preprocess a source file
src/lrp/tscfl_lrp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp.cpp.i
.PHONY : src/lrp/tscfl_lrp.cpp.i

src/lrp/tscfl_lrp.s: src/lrp/tscfl_lrp.cpp.s
.PHONY : src/lrp/tscfl_lrp.s

# target to generate assembly for a file
src/lrp/tscfl_lrp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp.cpp.s
.PHONY : src/lrp/tscfl_lrp.cpp.s

src/lrp/tscfl_lrp_balances.o: src/lrp/tscfl_lrp_balances.cpp.o
.PHONY : src/lrp/tscfl_lrp_balances.o

# target to build an object file
src/lrp/tscfl_lrp_balances.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp_balances.cpp.o
.PHONY : src/lrp/tscfl_lrp_balances.cpp.o

src/lrp/tscfl_lrp_balances.i: src/lrp/tscfl_lrp_balances.cpp.i
.PHONY : src/lrp/tscfl_lrp_balances.i

# target to preprocess a source file
src/lrp/tscfl_lrp_balances.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp_balances.cpp.i
.PHONY : src/lrp/tscfl_lrp_balances.cpp.i

src/lrp/tscfl_lrp_balances.s: src/lrp/tscfl_lrp_balances.cpp.s
.PHONY : src/lrp/tscfl_lrp_balances.s

# target to generate assembly for a file
src/lrp/tscfl_lrp_balances.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp_balances.cpp.s
.PHONY : src/lrp/tscfl_lrp_balances.cpp.s

src/lrp/tscfl_lrp_capacities.o: src/lrp/tscfl_lrp_capacities.cpp.o
.PHONY : src/lrp/tscfl_lrp_capacities.o

# target to build an object file
src/lrp/tscfl_lrp_capacities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp_capacities.cpp.o
.PHONY : src/lrp/tscfl_lrp_capacities.cpp.o

src/lrp/tscfl_lrp_capacities.i: src/lrp/tscfl_lrp_capacities.cpp.i
.PHONY : src/lrp/tscfl_lrp_capacities.i

# target to preprocess a source file
src/lrp/tscfl_lrp_capacities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp_capacities.cpp.i
.PHONY : src/lrp/tscfl_lrp_capacities.cpp.i

src/lrp/tscfl_lrp_capacities.s: src/lrp/tscfl_lrp_capacities.cpp.s
.PHONY : src/lrp/tscfl_lrp_capacities.s

# target to generate assembly for a file
src/lrp/tscfl_lrp_capacities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/lrp/tscfl_lrp_capacities.cpp.s
.PHONY : src/lrp/tscfl_lrp_capacities.cpp.s

src/solvers/tscfl_solver_benders.o: src/solvers/tscfl_solver_benders.cpp.o
.PHONY : src/solvers/tscfl_solver_benders.o

# target to build an object file
src/solvers/tscfl_solver_benders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_benders.cpp.o
.PHONY : src/solvers/tscfl_solver_benders.cpp.o

src/solvers/tscfl_solver_benders.i: src/solvers/tscfl_solver_benders.cpp.i
.PHONY : src/solvers/tscfl_solver_benders.i

# target to preprocess a source file
src/solvers/tscfl_solver_benders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_benders.cpp.i
.PHONY : src/solvers/tscfl_solver_benders.cpp.i

src/solvers/tscfl_solver_benders.s: src/solvers/tscfl_solver_benders.cpp.s
.PHONY : src/solvers/tscfl_solver_benders.s

# target to generate assembly for a file
src/solvers/tscfl_solver_benders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_benders.cpp.s
.PHONY : src/solvers/tscfl_solver_benders.cpp.s

src/solvers/tscfl_solver_cplex.o: src/solvers/tscfl_solver_cplex.cpp.o
.PHONY : src/solvers/tscfl_solver_cplex.o

# target to build an object file
src/solvers/tscfl_solver_cplex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_cplex.cpp.o
.PHONY : src/solvers/tscfl_solver_cplex.cpp.o

src/solvers/tscfl_solver_cplex.i: src/solvers/tscfl_solver_cplex.cpp.i
.PHONY : src/solvers/tscfl_solver_cplex.i

# target to preprocess a source file
src/solvers/tscfl_solver_cplex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_cplex.cpp.i
.PHONY : src/solvers/tscfl_solver_cplex.cpp.i

src/solvers/tscfl_solver_cplex.s: src/solvers/tscfl_solver_cplex.cpp.s
.PHONY : src/solvers/tscfl_solver_cplex.s

# target to generate assembly for a file
src/solvers/tscfl_solver_cplex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_cplex.cpp.s
.PHONY : src/solvers/tscfl_solver_cplex.cpp.s

src/solvers/tscfl_solver_subgradient.o: src/solvers/tscfl_solver_subgradient.cpp.o
.PHONY : src/solvers/tscfl_solver_subgradient.o

# target to build an object file
src/solvers/tscfl_solver_subgradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_subgradient.cpp.o
.PHONY : src/solvers/tscfl_solver_subgradient.cpp.o

src/solvers/tscfl_solver_subgradient.i: src/solvers/tscfl_solver_subgradient.cpp.i
.PHONY : src/solvers/tscfl_solver_subgradient.i

# target to preprocess a source file
src/solvers/tscfl_solver_subgradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_subgradient.cpp.i
.PHONY : src/solvers/tscfl_solver_subgradient.cpp.i

src/solvers/tscfl_solver_subgradient.s: src/solvers/tscfl_solver_subgradient.cpp.s
.PHONY : src/solvers/tscfl_solver_subgradient.s

# target to generate assembly for a file
src/solvers/tscfl_solver_subgradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/solvers/tscfl_solver_subgradient.cpp.s
.PHONY : src/solvers/tscfl_solver_subgradient.cpp.s

src/subproblem/tscfl_subproblem.o: src/subproblem/tscfl_subproblem.cpp.o
.PHONY : src/subproblem/tscfl_subproblem.o

# target to build an object file
src/subproblem/tscfl_subproblem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem.cpp.o
.PHONY : src/subproblem/tscfl_subproblem.cpp.o

src/subproblem/tscfl_subproblem.i: src/subproblem/tscfl_subproblem.cpp.i
.PHONY : src/subproblem/tscfl_subproblem.i

# target to preprocess a source file
src/subproblem/tscfl_subproblem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem.cpp.i
.PHONY : src/subproblem/tscfl_subproblem.cpp.i

src/subproblem/tscfl_subproblem.s: src/subproblem/tscfl_subproblem.cpp.s
.PHONY : src/subproblem/tscfl_subproblem.s

# target to generate assembly for a file
src/subproblem/tscfl_subproblem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem.cpp.s
.PHONY : src/subproblem/tscfl_subproblem.cpp.s

src/subproblem/tscfl_subproblem_dual.o: src/subproblem/tscfl_subproblem_dual.cpp.o
.PHONY : src/subproblem/tscfl_subproblem_dual.o

# target to build an object file
src/subproblem/tscfl_subproblem_dual.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_dual.cpp.o
.PHONY : src/subproblem/tscfl_subproblem_dual.cpp.o

src/subproblem/tscfl_subproblem_dual.i: src/subproblem/tscfl_subproblem_dual.cpp.i
.PHONY : src/subproblem/tscfl_subproblem_dual.i

# target to preprocess a source file
src/subproblem/tscfl_subproblem_dual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_dual.cpp.i
.PHONY : src/subproblem/tscfl_subproblem_dual.cpp.i

src/subproblem/tscfl_subproblem_dual.s: src/subproblem/tscfl_subproblem_dual.cpp.s
.PHONY : src/subproblem/tscfl_subproblem_dual.s

# target to generate assembly for a file
src/subproblem/tscfl_subproblem_dual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_dual.cpp.s
.PHONY : src/subproblem/tscfl_subproblem_dual.cpp.s

src/subproblem/tscfl_subproblem_net.o: src/subproblem/tscfl_subproblem_net.cpp.o
.PHONY : src/subproblem/tscfl_subproblem_net.o

# target to build an object file
src/subproblem/tscfl_subproblem_net.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_net.cpp.o
.PHONY : src/subproblem/tscfl_subproblem_net.cpp.o

src/subproblem/tscfl_subproblem_net.i: src/subproblem/tscfl_subproblem_net.cpp.i
.PHONY : src/subproblem/tscfl_subproblem_net.i

# target to preprocess a source file
src/subproblem/tscfl_subproblem_net.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_net.cpp.i
.PHONY : src/subproblem/tscfl_subproblem_net.cpp.i

src/subproblem/tscfl_subproblem_net.s: src/subproblem/tscfl_subproblem_net.cpp.s
.PHONY : src/subproblem/tscfl_subproblem_net.s

# target to generate assembly for a file
src/subproblem/tscfl_subproblem_net.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_net.cpp.s
.PHONY : src/subproblem/tscfl_subproblem_net.cpp.s

src/subproblem/tscfl_subproblem_primal.o: src/subproblem/tscfl_subproblem_primal.cpp.o
.PHONY : src/subproblem/tscfl_subproblem_primal.o

# target to build an object file
src/subproblem/tscfl_subproblem_primal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_primal.cpp.o
.PHONY : src/subproblem/tscfl_subproblem_primal.cpp.o

src/subproblem/tscfl_subproblem_primal.i: src/subproblem/tscfl_subproblem_primal.cpp.i
.PHONY : src/subproblem/tscfl_subproblem_primal.i

# target to preprocess a source file
src/subproblem/tscfl_subproblem_primal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_primal.cpp.i
.PHONY : src/subproblem/tscfl_subproblem_primal.cpp.i

src/subproblem/tscfl_subproblem_primal.s: src/subproblem/tscfl_subproblem_primal.cpp.s
.PHONY : src/subproblem/tscfl_subproblem_primal.s

# target to generate assembly for a file
src/subproblem/tscfl_subproblem_primal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/subproblem/tscfl_subproblem_primal.cpp.s
.PHONY : src/subproblem/tscfl_subproblem_primal.cpp.s

src/tscfl_instance.o: src/tscfl_instance.cpp.o
.PHONY : src/tscfl_instance.o

# target to build an object file
src/tscfl_instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/tscfl_instance.cpp.o
.PHONY : src/tscfl_instance.cpp.o

src/tscfl_instance.i: src/tscfl_instance.cpp.i
.PHONY : src/tscfl_instance.i

# target to preprocess a source file
src/tscfl_instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/tscfl_instance.cpp.i
.PHONY : src/tscfl_instance.cpp.i

src/tscfl_instance.s: src/tscfl_instance.cpp.s
.PHONY : src/tscfl_instance.s

# target to generate assembly for a file
src/tscfl_instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/tscfl_instance.cpp.s
.PHONY : src/tscfl_instance.cpp.s

src/tscfl_utils.o: src/tscfl_utils.cpp.o
.PHONY : src/tscfl_utils.o

# target to build an object file
src/tscfl_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/tscfl_utils.cpp.o
.PHONY : src/tscfl_utils.cpp.o

src/tscfl_utils.i: src/tscfl_utils.cpp.i
.PHONY : src/tscfl_utils.i

# target to preprocess a source file
src/tscfl_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/tscfl_utils.cpp.i
.PHONY : src/tscfl_utils.cpp.i

src/tscfl_utils.s: src/tscfl_utils.cpp.s
.PHONY : src/tscfl_utils.s

# target to generate assembly for a file
src/tscfl_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tscfl.dir/build.make CMakeFiles/tscfl.dir/src/tscfl_utils.cpp.s
.PHONY : src/tscfl_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tscfl"
	@echo "... tscfl_experiments"
	@echo "... experiments/tscfl_experiments.o"
	@echo "... experiments/tscfl_experiments.i"
	@echo "... experiments/tscfl_experiments.s"
	@echo "... src/lrp/tscfl_lrp.o"
	@echo "... src/lrp/tscfl_lrp.i"
	@echo "... src/lrp/tscfl_lrp.s"
	@echo "... src/lrp/tscfl_lrp_balances.o"
	@echo "... src/lrp/tscfl_lrp_balances.i"
	@echo "... src/lrp/tscfl_lrp_balances.s"
	@echo "... src/lrp/tscfl_lrp_capacities.o"
	@echo "... src/lrp/tscfl_lrp_capacities.i"
	@echo "... src/lrp/tscfl_lrp_capacities.s"
	@echo "... src/solvers/tscfl_solver_benders.o"
	@echo "... src/solvers/tscfl_solver_benders.i"
	@echo "... src/solvers/tscfl_solver_benders.s"
	@echo "... src/solvers/tscfl_solver_cplex.o"
	@echo "... src/solvers/tscfl_solver_cplex.i"
	@echo "... src/solvers/tscfl_solver_cplex.s"
	@echo "... src/solvers/tscfl_solver_subgradient.o"
	@echo "... src/solvers/tscfl_solver_subgradient.i"
	@echo "... src/solvers/tscfl_solver_subgradient.s"
	@echo "... src/subproblem/tscfl_subproblem.o"
	@echo "... src/subproblem/tscfl_subproblem.i"
	@echo "... src/subproblem/tscfl_subproblem.s"
	@echo "... src/subproblem/tscfl_subproblem_dual.o"
	@echo "... src/subproblem/tscfl_subproblem_dual.i"
	@echo "... src/subproblem/tscfl_subproblem_dual.s"
	@echo "... src/subproblem/tscfl_subproblem_net.o"
	@echo "... src/subproblem/tscfl_subproblem_net.i"
	@echo "... src/subproblem/tscfl_subproblem_net.s"
	@echo "... src/subproblem/tscfl_subproblem_primal.o"
	@echo "... src/subproblem/tscfl_subproblem_primal.i"
	@echo "... src/subproblem/tscfl_subproblem_primal.s"
	@echo "... src/tscfl_instance.o"
	@echo "... src/tscfl_instance.i"
	@echo "... src/tscfl_instance.s"
	@echo "... src/tscfl_utils.o"
	@echo "... src/tscfl_utils.i"
	@echo "... src/tscfl_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

