[metadata]
name = sscfl
version = attr: sscfl.VERSION
description = Solução do SSCFL por constraint programming.
author = Gabriel Braun
platforms = unix, linux
classifiers =
    Programming Language :: Python :: 3

[options]
packages =
    sscfl
package_dir =
    sscfl = src
install_requires =
    docplex>=2.30
    cplex>=22.1.2
include_package_data = True

[options.package_data]
* =
    *.txt

[options.entry_points]
console_scripts =
    sscfl_experiments = sscfl.experiments.sscfl_experiments:main
